In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/SemesterY_quiz_scores_anon.csv', sep=';')
display(df.head())

,Quiz,StudentID,Status,StartedAt,FinishedAt,Duration,Score/10.00,F 1 /0.59,F 2 /0.59,F 3 /0.59,...,F 4 /0.28,F 5 /2.50,F 6 /0.28,F 7 /0.56,F 8 /0.28,F 9 /2.22,F 10 /1.67,F 11 /0.28,F 12 /0.28,F 13 /0.28
0,Statistics,52894361d501e2f8cebf4e329e965fb4c05dedb4ab22d0...,Beendet,26.02. 10:27,27.02. 09:51,23 Stunden 24 Minuten,7.94,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Statistics,9739538f8be6eec8836a2c497c98e36c392cbb28c641a9...,Beendet,27.02. 09:31,27.02. 10:07,36 Minuten 14 Sekunden,6.68,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Statistics,68cfdbc505065daf7ec8084caf1178fdc250a27e1a8413...,Beendet,27.02. 14:12,27.02. 14:58,45 Minuten 36 Sekunden,5.98,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Statistics,eafc88d05fb3188aac74b6704cf9eba8f769f52f083531...,Beendet,01.03. 15:32,23.06. 09:28,113 Tage 16 Stunden,7.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Statistics,5de86005bd42f26bcec592ca8f00c954b09423d789ed68...,Beendet,01.03. 16:58,01.03. 17:35,37 Minuten 2 Sekunden,7.19,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = df.drop(columns=['Status', 'StartedAt', 'FinishedAt'])
display(df.head())

,Quiz,StudentID,Duration,Score/10.00,F 1 /0.59,F 2 /0.59,F 3 /0.59,F 4 /0.59,F 5 /0.59,F 6 /3.53,...,F 4 /0.28,F 5 /2.50,F 6 /0.28,F 7 /0.56,F 8 /0.28,F 9 /2.22,F 10 /1.67,F 11 /0.28,F 12 /0.28,F 13 /0.28
0,Statistics,52894361d501e2f8cebf4e329e965fb4c05dedb4ab22d0...,23 Stunden 24 Minuten,7.94,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Statistics,9739538f8be6eec8836a2c497c98e36c392cbb28c641a9...,36 Minuten 14 Sekunden,6.68,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Statistics,68cfdbc505065daf7ec8084caf1178fdc250a27e1a8413...,45 Minuten 36 Sekunden,5.98,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Statistics,eafc88d05fb3188aac74b6704cf9eba8f769f52f083531...,113 Tage 16 Stunden,7.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Statistics,5de86005bd42f26bcec592ca8f00c954b09423d789ed68...,37 Minuten 2 Sekunden,7.19,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
quiz_names = df['Quiz'].unique()
quiz_dfs = {}

for quiz_name in quiz_names:
    quiz_dfs[quiz_name] = df[df['Quiz'] == quiz_name].copy()

The DataFrame has been split into separate DataFrames based on the 'Quiz' column. You can access them through the `quiz_dfs` dictionary. For example, to see the 'Statistics' quiz data:

In [5]:
quiz_dfs.keys()

dict_keys(['Statistics', 'predictive analytics', 'Evaluation', 'MDM', 'Regression'])

In [6]:
if 'Statistics' in quiz_dfs:
    print("First 5 rows of 'Statistics' Quiz DataFrame:")
    display(quiz_dfs['Statistics'].head())
else:
    print("No 'Statistics' quiz found in the data.")

First 5 rows of 'Statistics' Quiz DataFrame:

,Quiz,StudentID,Duration,Score/10.00,F 1 /0.59,F 2 /0.59,F 3 /0.59,F 4 /0.59,F 5 /0.59,F 6 /3.53,...,F 4 /0.28,F 5 /2.50,F 6 /0.28,F 7 /0.56,F 8 /0.28,F 9 /2.22,F 10 /1.67,F 11 /0.28,F 12 /0.28,F 13 /0.28
0,Statistics,52894361d501e2f8cebf4e329e965fb4c05dedb4ab22d0...,23 Stunden 24 Minuten,7.94,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Statistics,9739538f8be6eec8836a2c497c98e36c392cbb28c641a9...,36 Minuten 14 Sekunden,6.68,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Statistics,68cfdbc505065daf7ec8084caf1178fdc250a27e1a8413...,45 Minuten 36 Sekunden,5.98,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Statistics,eafc88d05fb3188aac74b6704cf9eba8f769f52f083531...,113 Tage 16 Stunden,7.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Statistics,5de86005bd42f26bcec592ca8f00c954b09423d789ed68...,37 Minuten 2 Sekunden,7.19,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Drop all question-columns that don't belong to that question

In [7]:
for quiz_name, quiz_df in quiz_dfs.items():
    quiz_dfs[quiz_name] = quiz_df.dropna(axis=1, how='all')

print("DataFrames after dropping all-NaN columns:")
if 'Statistics' in quiz_dfs:
    print("First 5 rows of 'Statistics' Quiz DataFrame after cleaning:")
    display(quiz_dfs['Statistics'].head())
else:
    print("No 'Statistics' quiz found in the data.")

DataFrames after dropping all-NaN columns:
First 5 rows of 'Statistics' Quiz DataFrame after cleaning:

,Quiz,StudentID,Duration,Score/10.00,F 1 /0.63,F 2 /0.63,F 3 /0.63,F 4 /0.63,F 5 /0.63,F 6 /0.63,F 7 /0.63,F 8 /0.63,F 9 /0.63,F 10 /0.63,F 11 /0.63,F 12 /0.63,F 13 /0.63,F 14 /0.63,F 15 /0.63,F 16 /0.63
0,Statistics,52894361d501e2f8cebf4e329e965fb4c05dedb4ab22d0...,23 Stunden 24 Minuten,7.94,0.42,0.63,0.63,0.63,0.62,0.63,0.63,0.63,0.21,0.63,0.17,0.47,0.29,0.42,0.63,0.35
1,Statistics,9739538f8be6eec8836a2c497c98e36c392cbb28c641a9...,36 Minuten 14 Sekunden,6.68,0.63,0.42,0.63,0.63,0.42,0.21,0.42,0.63,0.63,0.63,0.13,0.42,0.5,0,0.16,0.28
2,Statistics,68cfdbc505065daf7ec8084caf1178fdc250a27e1a8413...,45 Minuten 36 Sekunden,5.98,0.63,0.52,0.63,0.63,0.42,0.63,0,0.63,0,0.63,0.25,0,0,0.21,0.63,0.21
3,Statistics,eafc88d05fb3188aac74b6704cf9eba8f769f52f083531...,113 Tage 16 Stunden,7.4,0.42,0.52,0.63,0.42,0.62,0.63,0.63,0.63,0.63,0.63,0,0.16,0.42,0.63,0.47,0
4,Statistics,5de86005bd42f26bcec592ca8f00c954b09423d789ed68...,37 Minuten 2 Sekunden,7.19,0.63,0.63,0.63,0.63,0.62,0.42,0.63,0.63,0.63,0.52,0,0.08,0.5,0.31,0.16,0.21

In [8]:
import re

def duration_to_minutes(duration_str):
    """
    Converts a duration string (e.g., '23 Stunden 24 Minuten') to total minutes.
    Handles Stunden, Minuten, and Sekunden.
    """
    total_minutes = 0
    if isinstance(duration_str, str):
        hours_match = re.search(r'(\d+)\s*Stunden', duration_str)
        minutes_match = re.search(r'(\d+)\s*Minuten', duration_str)
        seconds_match = re.search(r'(\d+)\s*Sekunden', duration_str)

        if hours_match:
            total_minutes += int(hours_match.group(1)) * 60
        if minutes_match:
            total_minutes += int(minutes_match.group(1))
        if seconds_match:
            total_minutes += int(seconds_match.group(1)) / 60
    return total_minutes

for quiz_name, quiz_df_orig in quiz_dfs.items():
    # Create a working copy to avoid modifying the original dictionary entry mid-loop before final assignment
    quiz_df = quiz_df_orig.copy()

    # 1. Drop attempts where duration is less than a minute
    quiz_df.loc[:, 'Duration_minutes'] = quiz_df['Duration'].apply(duration_to_minutes)
    quiz_df = quiz_df[quiz_df['Duration_minutes'] >= 1].drop(columns=['Duration_minutes'])

    # 2. Drop attempts where Score/10.00 is 0
    quiz_df = quiz_df[quiz_df['Score/10.00'] != 0]

    # 3. Transform 'F x /y.yy' columns to relative scores (0 to 1)
    # Identify columns that match the 'F x /y.yy' pattern
    fx_columns = [col for col in quiz_df.columns if re.match(r'^F\s\d+\s/\d+\.\d+$', col)]

    for col in fx_columns:
        try:
            # Extract the max score (y.yy) from the column name
            max_score = float(col.split('/')[-1])
            if max_score > 0:
                quiz_df.loc[:, col] = quiz_df[col].astype(float) / max_score
                # Rename the column to a simpler format
                new_col_name = col.split('/')[0].strip()
                quiz_df = quiz_df.rename(columns={col: new_col_name})
            else:
                # If max_score is 0, these columns are usually all NaN or 0, so convert to NaN or leave as is if already processed.
                # For simplicity, if max_score is 0, we can fill with 0 or NaN as it implies no score possible or relevant.
                quiz_df.loc[:, col] = 0.0 # Or pd.NA or leave as is if already 0/NaN
                new_col_name = col.split('/')[0].strip()
                quiz_df = quiz_df.rename(columns={col: new_col_name})
        except (ValueError, IndexError):
            # Handle cases where parsing max_score fails or column name is malformed
            print(f"Warning: Could not process column {col} in quiz {quiz_name}")

    quiz_dfs[quiz_name] = quiz_df.copy()

print("DataFrames after applying all cleaning and transformations:")
if 'Statistics' in quiz_dfs:
    print("First 5 rows of 'Statistics' Quiz DataFrame after full cleaning:")
    display(quiz_dfs['Statistics'].head())
else:
    print("No 'Statistics' quiz found in the data.")

DataFrames after applying all cleaning and transformations:
First 5 rows of 'Statistics' Quiz DataFrame after full cleaning:

,Quiz,StudentID,Duration,Score/10.00,F 1,F 2,F 3,F 4,F 5,F 6,F 7,F 8,F 9,F 10,F 11,F 12,F 13,F 14,F 15,F 16
0,Statistics,52894361d501e2f8cebf4e329e965fb4c05dedb4ab22d0...,23 Stunden 24 Minuten,7.94,0.666667,1.0,1.0,1.0,0.984127,1.0,1.0,1.0,0.333333,1.0,0.269841,0.746032,0.460317,0.666667,1.0,0.555556
1,Statistics,9739538f8be6eec8836a2c497c98e36c392cbb28c641a9...,36 Minuten 14 Sekunden,6.68,1.0,0.666667,1.0,1.0,0.666667,0.333333,0.666667,1.0,1.0,1.0,0.206349,0.666667,0.793651,0.0,0.253968,0.444444
2,Statistics,68cfdbc505065daf7ec8084caf1178fdc250a27e1a8413...,45 Minuten 36 Sekunden,5.98,1.0,0.825397,1.0,1.0,0.666667,1.0,0.0,1.0,0.0,1.0,0.396825,0.0,0.0,0.333333,1.0,0.333333
3,Statistics,eafc88d05fb3188aac74b6704cf9eba8f769f52f083531...,113 Tage 16 Stunden,7.4,0.666667,0.825397,1.0,0.666667,0.984127,1.0,1.0,1.0,1.0,1.0,0.0,0.253968,0.666667,1.0,0.746032,0.0
4,Statistics,5de86005bd42f26bcec592ca8f00c954b09423d789ed68...,37 Minuten 2 Sekunden,7.19,1.0,1.0,1.0,1.0,0.984127,0.666667,1.0,1.0,1.0,0.825397,0.0,0.126984,0.793651,0.492063,0.253968,0.333333

### Aggregate student performance for each quiz

Now, for each quiz DataFrame, we will create a new DataFrame that summarizes each student's performance. This will include:

*   **StudentID**: Unique identifier for each student.
*   **Attempts**: The number of times the student attempted the quiz.
*   **Overall Score Statistics**: Mean, Max, and Min of 'Score/10.00' across all attempts.
*   **Question Score Statistics**: Mean, Max, and Min for each individual question (e.g., 'F 1', 'F 2') across all attempts.

In [9]:
processed_quiz_dfs = {}

for quiz_name, quiz_df in quiz_dfs.items():
    # Identify 'F x' columns
    fx_columns = [col for col in quiz_df.columns if re.match(r'^F\s\d+$', col)]

    # Ensure 'Score/10.00' and 'F x' columns are numeric
    quiz_df.loc[:, 'Score/10.00'] = pd.to_numeric(quiz_df['Score/10.00'], errors='coerce')
    for col in fx_columns:
        quiz_df.loc[:, col] = pd.to_numeric(quiz_df[col], errors='coerce')

    # Define aggregation dictionary
    agg_dict = {
        'Score/10.00': ['count', 'mean', 'max', 'min']
    }
    for col in fx_columns:
        agg_dict[col] = ['mean', 'max', 'min']

    # Group by StudentID and apply aggregations
    processed_df = quiz_df.groupby('StudentID').agg(agg_dict)

    # Flatten MultiIndex columns and rename for clarity
    processed_df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in processed_df.columns.values]
    processed_df = processed_df.rename(columns={'Score/10.00_count': 'Attempts'})
    processed_df = processed_df.reset_index()

    processed_quiz_dfs[quiz_name] = processed_df

print("Processed DataFrames created. Displaying head of 'Statistics' processed data:")
if 'Statistics' in processed_quiz_dfs:
    display(processed_quiz_dfs['Statistics'].head())
else:
    print("No 'Statistics' quiz found in processed data.")

Processed DataFrames created. Displaying head of 'Statistics' processed data:

,StudentID,Attempts,Score/10.00_mean,Score/10.00_max,Score/10.00_min,F 1_mean,F 1_max,F 1_min,F 2_mean,F 2_max,...,F 13_min,F 14_mean,F 14_max,F 14_min,F 15_mean,F 15_max,F 15_min,F 16_mean,F 16_max,F 16_min
0,0364dd853e3d05dd749ae2a991c62129e91a60615aaa61...,3,5.53,8.33,0.21,0.666667,1.0,0.333333,0.555556,1.0,...,0.0,0.666667,1.0,0.0,0.582011,1.0,0.0,0.333333,0.555556,0.0
1,0bc517c5d0fa5994bc330b1e80d51aacd3cdc3f9d83df3...,2,3.595,5.34,1.85,0.666667,1.0,0.333333,0.746032,0.825397,...,0.0,0.126984,0.253968,0.0,0.126984,0.253968,0.0,0.166667,0.333333,0.0
2,0bc8b1f357e2fb4364b05bc6ea79361312e15630a74385...,1,5.16,5.16,5.16,0.666667,0.666667,0.666667,1.0,1.0,...,0.269841,0.0,0.0,0.0,0.492063,0.492063,0.492063,0.0,0.0,0.0
3,0f786c0502fad70b008537fce2e6b0ad7611fed7357721...,2,8.69,9.51,7.87,0.746032,1.0,0.492063,0.912698,1.0,...,0.666667,0.833333,1.0,0.666667,1.0,1.0,1.0,0.5,0.555556,0.444444
4,21989da1f74e1e8d707cf63b8acbceff36517bca0fd52b...,1,6.62,6.62,6.62,1.0,1.0,1.0,1.0,1.0,...,0.206349,1.0,1.0,1.0,0.746032,0.746032,0.746032,0.333333,0.333333,0.333333

### Export Processed DataFrames to CSV

Now, we will export each of the `processed_quiz_dfs` into separate CSV files for further analysis or storage. Each file will be named according to its corresponding quiz.

In [10]:
import os

output_directory = 'data/processed_quiz_data'
os.makedirs(output_directory, exist_ok=True)

print("Exporting processed quiz data to CSV files...")

for quiz_name, processed_df in processed_quiz_dfs.items():
    # Sanitize quiz_name for filename (replace spaces with underscores, etc.)
    sanitized_quiz_name = quiz_name.replace(' ', '_').replace('/', '_').replace(':', '_').lower()
    output_filename = f'{output_directory}/{sanitized_quiz_name}_processed_scores.csv'
    processed_df.to_csv(output_filename, index=False)
    print(f"Exported '{quiz_name}' to {output_filename}")

print("All processed quiz DataFrames exported.")

Exporting processed quiz data to CSV files...
Exported 'Statistics' to data/processed_quiz_data/statistics_processed_scores.csv
Exported 'predictive analytics' to data/processed_quiz_data/predictive_analytics_processed_scores.csv
Exported 'Evaluation' to data/processed_quiz_data/evaluation_processed_scores.csv
Exported 'MDM' to data/processed_quiz_data/mdm_processed_scores.csv
Exported 'Regression' to data/processed_quiz_data/regression_processed_scores.csv
All processed quiz DataFrames exported.

### Combine All Processed Quiz DataFrames

Now, we will merge all the individual processed quiz DataFrames into a single, comprehensive DataFrame. This will allow for consolidated analysis of student performance across all quizzes. To ensure clarity, all columns (except 'StudentID') will be prefixed with their respective quiz name.

In [11]:
merged_df = None

for quiz_name, processed_df in processed_quiz_dfs.items():
    # Make a copy to avoid modifying the original dictionary entries
    df_to_merge = processed_df.copy()

    # Sanitize quiz_name for column prefix
    sanitized_quiz_name = quiz_name.replace(' ', '_').replace('/', '_').replace(':', '_').lower()

    # Rename columns to include quiz_name as prefix, except for 'StudentID'
    new_columns = {col: f'{sanitized_quiz_name}_{col}' for col in df_to_merge.columns if col != 'StudentID'}
    df_to_merge = df_to_merge.rename(columns=new_columns)

    if merged_df is None:
        merged_df = df_to_merge
    else:
        # Use an outer join to include all students from all quizzes
        merged_df = pd.merge(merged_df, df_to_merge, on='StudentID', how='outer')

print("Merged DataFrame created. Displaying head:")
display(merged_df.head())

Merged DataFrame created. Displaying head:

,StudentID,statistics_Attempts,statistics_Score/10.00_mean,statistics_Score/10.00_max,statistics_Score/10.00_min,statistics_F 1_mean,statistics_F 1_max,statistics_F 1_min,statistics_F 2_mean,statistics_F 2_max,...,regression_F 10_min,regression_F 11_mean,regression_F 11_max,regression_F 11_min,regression_F 12_mean,regression_F 12_max,regression_F 12_min,regression_F 13_mean,regression_F 13_max,regression_F 13_min
0,0364dd853e3d05dd749ae2a991c62129e91a60615aaa61...,3.0,5.53,8.33,0.21,0.666667,1.0,0.333333,0.555556,1.0,...,0.0,0.559524,1.0,0.0,0.666667,1.0,0.0,0.666667,1.0,0.0
1,0bc517c5d0fa5994bc330b1e80d51aacd3cdc3f9d83df3...,2.0,3.595,5.34,1.85,0.666667,1.0,0.333333,0.746032,0.825397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0bc8b1f357e2fb4364b05bc6ea79361312e15630a74385...,1.0,5.16,5.16,5.16,0.666667,0.666667,0.666667,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0d5ff4f2bbe755d62015a8ec11fdbdf45e16cfa547d1b5...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,0f786c0502fad70b008537fce2e6b0ad7611fed7357721...,2.0,8.69,9.51,7.87,0.746032,1.0,0.492063,0.912698,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
output_filename = 'data/Processed_Data.csv'
merged_df.to_csv(output_filename, index=False)
print(f"Merged DataFrame exported to {output_filename}")

Merged DataFrame exported to data/Processed_Data.csv